- src/main/webapp/WEB-INF/tags/layout.tag
- src/main/webapp/partials/footer.jsp
- src/main/webapp/partials/header.jsp
Aggiunto header e footer al sito.
- [2 ] Nuove funzionalità:
Header per la gestione della navigazione
Footer per link utili per il supporto
> Added header and footer

- .travis.yml
Fix a travis error for fixing build
> revision travis

- src/main/java/it/blackhat/symposium/models/User.java
- src/main/java/it/blackhat/symposium/models/UserModel.java
Add User interface and UserModel class.
> Add User interface and UserModel class.

- .checkstyle
- src/main/java/it/blackhat/symposium/actions/admin/SigninAdminAction.java
- src/main/java/it/blackhat/symposium/managers/AdminManager.java
- src/main/java/it/blackhat/symposium/managers/AdminModelManager.java
- src/main/webapp/WEB-INF/web.xml
AdminManager, Model Completed
Created the methods:
-findAdminBy 
-banUser
-genReport
> AdminManager Completed

- src/main/java/it/blackhat/symposium/actions/admin/SigninAdminAction.java
- src/main/java/it/blackhat/symposium/managers/AdminManager.java
- src/main/java/it/blackhat/symposium/managers/AdminModelManager.java
- src/main/java/it/blackhat/symposium/managers/UserManager.java
- src/main/java/it/blackhat/symposium/managers/UserModelManager.java
- src/main/webapp/index.jsp
Added UserManager, UserModelManage
Mofied AdminManager, AdminModelManager
Added the Interface UserManager and the class UserModelManager
Modified the method in AdminManager and AdminModelManager
> Added User Modified Admin

- src/main/webapp/partials/header.jsp
- src/main/webapp/profile.jsp
- src/main/webapp/signIn.jsp
- src/main/webapp/support.jsp
I've made some minor  formatting fixes on the existing pages
- [1] Bug fix (non-breaking change which fixes an issue)
+For some reason the index would not let me redirect to the sign in page, it's fixed now
> Smaller formatting fixes

- .checkstyle
- src/main/java/it/blackhat/symposium/filters/AdminLogInFilter.java
- src/main/java/it/blackhat/symposium/filters/UserLogInFilter.java
Added AdminLoginInFilter and UserLogInFilter
Added UserLogInFilter class
Added AdminLogInFilter class
> Added Filters

- src/main/java/it/blackhat/symposium/managers/AdminManager.java
- src/main/java/it/blackhat/symposium/managers/AdminModelManager.java
- src/main/java/it/blackhat/symposium/managers/UserManager.java
- src/main/java/it/blackhat/symposium/managers/UserModelManager.java
Modification to:
UserManager, UserModelManager, AdminManager, AdminModelManager
Modification to the Methods in UserManager and UserModelManager
Minor changes in AdminManager and AdminModelManager
> Modification to Admin and User Manager

- src/main/java/it/blackhat/symposium/actions/ActionFactory.java
- src/main/java/it/blackhat/symposium/actions/admin/AdminActionFactory.java
- src/main/java/it/blackhat/symposium/actions/guest/SigninAction.java
- src/main/java/it/blackhat/symposium/actions/guest/SignupAction.java
- src/main/java/it/blackhat/symposium/actions/question/DeleteQuestionAction.java
- src/main/java/it/blackhat/symposium/actions/question/DeleteQuestionAdminAction.java
- src/main/java/it/blackhat/symposium/actions/question/InsertQuestionAction.java
- src/main/java/it/blackhat/symposium/actions/question/ModifyTagQuestionAdminAction.java
- src/main/java/it/blackhat/symposium/actions/question/QuestionActionFactory.java
- src/main/java/it/blackhat/symposium/actions/question/ReportQuestionAction.java
- src/main/java/it/blackhat/symposium/actions/user/UserActionFactory.java
- src/main/java/it/blackhat/symposium/controllers/AdminController.java
- src/main/java/it/blackhat/symposium/controllers/DispatcherController.java
- src/main/java/it/blackhat/symposium/controllers/QuestionController.java
- src/main/java/it/blackhat/symposium/controllers/UserController.java
- src/main/java/it/blackhat/symposium/filters/AdminLogInFilter.java
- src/main/java/it/blackhat/symposium/helpers/InvalidActionException.java
Added QuestionController and other prototypes
Added InvalidActionException
Fixed factories with the new exception
> Added prototypes, factories fix and new exception

- src/main/webapp/WEB-INF/tags/question.tag
- src/main/webapp/index.jsp
Index dinamic and question tag
> Index, question tag

- src/main/webapp/index.jsp
> Fixed index

- src/main/webapp/META-INF/context.xml
- src/main/webapp/error404.jsp
> Addedd error404.jsp page

- src/main/java/it/blackhat/symposium/managers/AdminManager.java
- src/main/java/it/blackhat/symposium/managers/AdminModelManager.java
- src/main/java/it/blackhat/symposium/managers/UserManager.java
- src/main/java/it/blackhat/symposium/managers/UserModelManager.java
- src/main/java/it/blackhat/symposium/queries/AdminQuery.java
- src/main/java/it/blackhat/symposium/queries/UserQuery.java
Added query to the methods in AdminModelManager and UserModelManager, changed some paramether in AdminManager and UserManager
Added Query to the methods in:
-AdminModelManager;
-UserModelManager.
Changed some parameter in:
-AdminManager;
-UserManager;
-AdminQuery;
-UserQuery.
> Added Query

- src/main/webapp/partials/header.jsp
- src/main/webapp/signIn.jsp
- src/main/webapp/signUp.jsp
I've added a Sign Up page and did other minor fixes
+Fixed the sign in page not displaying the corretc input types
+Fixed the link in the header
+Added a stub sign up page
> Sign Up page and other minor fixes

- src/main/webapp/partials/header.jsp
The nav was glitched and did not display correctly, it's fixed now
+Re-written a "div" to "nav" to display properly the navigational bar
> Fixed nav glitch

- src/main/java/it/blackhat/symposium/models/Answer.java
- src/main/java/it/blackhat/symposium/models/AnswerModel.java
- src/main/java/it/blackhat/symposium/models/Question.java
- src/main/java/it/blackhat/symposium/models/QuestionModel.java
Added the Question and the Answer model
> Question and Answer model

- src/main/java/it/blackhat/symposium/managers/QuestionManager.java
- src/main/java/it/blackhat/symposium/managers/QuestionModelManager.java
- src/main/java/it/blackhat/symposium/queries/QuestionQuery.java
- src/main/java/it/blackhat/symposium/queries/TagQuery.java
I added tagQuery, QuestionManager,QuestionModelManager and fixes questionQuery
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds
> added classes

- src/main/java/it/blackhat/symposium/actions/answer/AnswerActionFactory.java
- src/main/java/it/blackhat/symposium/actions/answer/DeleteAnswerAdminAction.java
- src/main/java/it/blackhat/symposium/actions/question/DeleteQuestionAdminAction.java
- src/main/java/it/blackhat/symposium/actions/question/QuestionActionFactory.java
- src/main/java/it/blackhat/symposium/managers/QuestionManager.java
- src/main/java/it/blackhat/symposium/managers/QuestionModelManager.java
Almost created DeleteQuestionAction for both users (simple and admin), fixed comments and added the admin actions.
> Added DeleteQuestionAction, fixed comments and added admin actions.

- src/main/java/it/blackhat/symposium/actions/guest/SigninAction.java
- src/main/java/it/blackhat/symposium/actions/question/DeleteQuestionAction.java
- src/main/java/it/blackhat/symposium/actions/question/DeleteQuestionAdminAction.java
- src/main/java/it/blackhat/symposium/actions/question/InsertQuestionAction.java
- src/main/java/it/blackhat/symposium/actions/user/DeleteAccountAction.java
- src/main/java/it/blackhat/symposium/controllers/GuestController.java
- src/main/java/it/blackhat/symposium/managers/AdminManager.java
- src/main/java/it/blackhat/symposium/managers/AdminModelManager.java
- src/main/java/it/blackhat/symposium/managers/QuestionModelManager.java
- src/main/java/it/blackhat/symposium/managers/TagManager.java
- src/main/java/it/blackhat/symposium/managers/TagModelManager.java
- src/main/java/it/blackhat/symposium/managers/UserModelManager.java
- src/main/java/it/blackhat/symposium/models/Admin.java
- src/main/java/it/blackhat/symposium/models/AdminModel.java
- src/main/java/it/blackhat/symposium/models/Answer.java
- src/main/java/it/blackhat/symposium/models/AnswerModel.java
- src/main/java/it/blackhat/symposium/models/Question.java
- src/main/java/it/blackhat/symposium/models/QuestionModel.java
- src/main/java/it/blackhat/symposium/models/Tag.java
- src/main/java/it/blackhat/symposium/models/TagModel.java
- src/main/java/it/blackhat/symposium/queries/TagQuery.java
Refactor of question, answer and tag models, fixes in build and checkstyle.
> Pulicanbranch

- src/main/java/it/blackhat/symposium/managers/AnswerManager.java
- src/main/java/it/blackhat/symposium/managers/AnswerModelManager.java
- src/main/java/it/blackhat/symposium/managers/ConnectionManager.java
- src/main/java/it/blackhat/symposium/managers/QuestionManager.java
- src/main/java/it/blackhat/symposium/managers/QuestionModelManager.java
- src/main/java/it/blackhat/symposium/managers/TagModelManager.java
- src/main/java/it/blackhat/symposium/managers/UserManager.java
- src/main/java/it/blackhat/symposium/managers/UserModelManager.java
- src/main/java/it/blackhat/symposium/models/Admin.java
- src/main/java/it/blackhat/symposium/models/AdminModel.java
- src/main/java/it/blackhat/symposium/models/Answer.java
- src/main/java/it/blackhat/symposium/models/AnswerModel.java
- src/main/java/it/blackhat/symposium/models/Question.java
- src/main/java/it/blackhat/symposium/models/QuestionModel.java
- src/main/java/it/blackhat/symposium/models/Report.java
- src/main/java/it/blackhat/symposium/models/Tag.java
- src/main/java/it/blackhat/symposium/models/TagModel.java
- src/main/java/it/blackhat/symposium/models/User.java
- src/main/java/it/blackhat/symposium/models/UserModel.java
Added SeachQuestionByTag and SeachQuestionByWords in QuestionManager and QuestionModelManager
Added seachQuestionByTag and seachQuestionByWords in QuestionManager
Added implementation of this methods in QuestionModelManager
> Added SeachMethods in QuestionManager

- src/main/java/it/blackhat/symposium/actions/answer/AnswerActionFactory.java
- src/main/java/it/blackhat/symposium/actions/answer/DeleteAnswerAction.java
- src/main/java/it/blackhat/symposium/actions/answer/DeleteAnswerAdminAction.java
- src/main/java/it/blackhat/symposium/actions/answer/InsertAnswerAction.java
- src/main/java/it/blackhat/symposium/actions/guest/GuestActionFactory.java
- src/main/java/it/blackhat/symposium/managers/AnswerManager.java
- src/main/java/it/blackhat/symposium/managers/UserModelManager.java
- src/main/java/it/blackhat/symposium/models/AdminModel.java
- src/main/java/it/blackhat/symposium/models/AnswerModel.java
- src/main/java/it/blackhat/symposium/models/QuestionModel.java
- src/main/java/it/blackhat/symposium/models/Report.java
- src/main/java/it/blackhat/symposium/models/ReportModel.java
- src/main/java/it/blackhat/symposium/models/StatsModel.java
- src/main/java/it/blackhat/symposium/models/TagModel.java
- src/main/java/it/blackhat/symposium/models/UserModel.java
Fixed various checkstyle errors, fixed models and added bean validators
> Fixed models and added bean validators

- src/main/java/it/blackhat/symposium/queries/UserQuery.java
- src/main/webapp/assets/index.css
- src/main/webapp/assets/index.js
- src/main/webapp/dashboard.jsp
- src/main/webapp/faq.jsp
- src/main/webapp/partials/footer.jsp
New Features: Handling checkboxes, New admin dashboard
Added new jsp pages and checkbox handling
> Fix: Footer, FAQ, UserQuery

- src/main/java/it/blackhat/symposium/queries/AdminQuery.java
- src/main/java/it/blackhat/symposium/queries/AnswerQuery.java
- src/main/java/it/blackhat/symposium/queries/QuestionQuery.java
- src/main/java/it/blackhat/symposium/queries/TagQuery.java
- src/main/java/it/blackhat/symposium/queries/UserQuery.java
- src/main/webapp/WEB-INF/tags/userOverview.tag
- src/main/webapp/userList.jsp
I fixed: AdminQuery,AnswerQuery,QuestionQuery,TagQuery,UserQuery, and i create: userOverview.tag, userList.jsp
> Fix: AdminQuery,AnswerQuery,QuestionQuery,TagQuery,UserQuery

- src/main/java/it/blackhat/symposium/actions/answer/ChooseBestAnswerAction.java
- src/main/java/it/blackhat/symposium/actions/answer/DeleteAnswerAction.java
Added ChooseBestAnswerAction.java
> Added BestAnswer action

- src/main/java/it/blackhat/symposium/actions/answer/ChooseBestAnswerAction.java
- src/main/java/it/blackhat/symposium/actions/guest/SignupAction.java
> Fixed error in checkstyle

- src/main/java/it/blackhat/symposium/controllers/GuestController.java
- src/main/java/it/blackhat/symposium/controllers/UserController.java
- src/main/java/it/blackhat/symposium/filters/AdminLogInFilter.java
- src/main/java/it/blackhat/symposium/filters/UserLogInFilter.java
- src/main/webapp/signIn.jsp
- src/main/webapp/signUp.jsp
I gave a name to web services and filters, fixed signup and signin pages and comments
> Named web services, fixed comments, fixed signup and signin pages

- src/main/java/it/blackhat/symposium/actions/admin/ReportAction.java
- src/main/java/it/blackhat/symposium/actions/admin/ReportStatsAction.java
- src/main/java/it/blackhat/symposium/actions/guest/IncrementUsersCount.java
- src/main/java/it/blackhat/symposium/managers/StatsManager.java
- src/main/java/it/blackhat/symposium/managers/StatsModelManager.java
- src/main/java/it/blackhat/symposium/queries/StatsQuery.java
- src/main/webapp/editProfile.jsp
- src/main/webapp/faq.jsp
- src/main/webapp/signIn.jsp
1. Added a stub ReportAction.java
2. Added a IncrementUsersCount.Java class
3. Added a StatManagaer.java interface
4. Added a StatsModelManager.java class
5. Modified the editProfile.jsp a bit for the task
> Varius classes added+ modified editProfile.jsp

- pom.xml
- src/main/webapp/WEB-INF/tags/answer.tag
- src/main/webapp/WEB-INF/tags/questionDetails.tag
- src/main/webapp/WEB-INF/tags/tagDetails.tag
> add custom tags and new Question

- src/main/java/it/blackhat/symposium/actions/user/ShowProfileAction.java
- src/main/java/it/blackhat/symposium/actions/user/UserActionFactory.java
- src/main/webapp/editProfile.jsp
- src/main/webapp/error400.jsp
- src/main/webapp/error401.jsp
- src/main/webapp/profile.jsp
Added ShowProfileAction and fixed profile and error page.
> Added ShowProfileAction and fixed profile and error page.

- src/main/java/it/blackhat/symposium/actions/question/QuestionActionFactory.java
- src/main/java/it/blackhat/symposium/actions/question/ShowQuestionAction.java
- src/main/webapp/WEB-INF/tags/answer.tag
- src/main/webapp/WEB-INF/tags/questionDetails.tag
> add answer tag and action

- src/main/java/it/blackhat/symposium/queries/AnswerQuery.java
- src/main/java/it/blackhat/symposium/queries/TagQuery.java
Added new Queries: TakeTag and TakeAnswers
> Added new Queries

- src/main/java/it/blackhat/symposium/queries/QuestionQuery.java
Added new Query: Take Questions;
> Added new Query: Take Questions

- src/main/java/it/blackhat/symposium/actions/guest/GuestActionFactory.java
- src/main/java/it/blackhat/symposium/actions/question/QuestionActionFactory.java
- src/main/java/it/blackhat/symposium/actions/question/SeachQuestionsBy.java
- src/main/java/it/blackhat/symposium/managers/QuestionModelManager.java
- src/main/java/it/blackhat/symposium/queries/QuestionQuery.java
- src/main/webapp/META-INF/context.xml
- src/main/webapp/partials/header.jsp
Added SeachQuestionsBy class
Added QuestionActionFactory call
Modified QuestionQuery, QuestionModelManager methods, context, GuestActionFactory
Added Class SeachQuestionsBy
Added Call to SeachQuestionsBy in QuestionActionFactory and GuestActionFactory
Fixed QuestionQuery, header, context, QuestionModelManager Methods
> BackEnd SeachBy

- src/main/java/it/blackhat/symposium/managers/AdminManager.java
- src/main/java/it/blackhat/symposium/managers/AdminModelManager.java
- src/main/java/it/blackhat/symposium/queries/AdminQuery.java
- src/main/java/it/blackhat/symposium/queries/AnswerQuery.java
- src/main/java/it/blackhat/symposium/queries/QuestionQuery.java
- src/main/java/it/blackhat/symposium/queries/StatsQuery.java
- src/main/java/it/blackhat/symposium/queries/TagQuery.java
- src/main/java/it/blackhat/symposium/queries/UserQuery.java
- src/main/webapp/adminSignup.jsp
- src/main/webapp/partials/header.jsp
Add signinadmin page and fix query length
> fix query order, add signinadmin, remove unusued method

- src/main/java/it/blackhat/symposium/actions/admin/BanAction.java
- src/main/java/it/blackhat/symposium/managers/AdminManager.java
- src/main/java/it/blackhat/symposium/managers/AdminModelManager.java
- src/main/java/it/blackhat/symposium/managers/UserManager.java
- src/main/java/it/blackhat/symposium/managers/UserModelManager.java
- src/main/java/it/blackhat/symposium/queries/AdminQuery.java
- src/main/java/it/blackhat/symposium/queries/UserQuery.java
Refactor ban user for better responsability
> refactor banuser

- src/main/java/it/blackhat/symposium/actions/question/SeachQuestionsBy.java
Fix to SeachQuestionsBy
Bug fix to SeachQuestionsBy
> Fix SeachQuestionsBy

- src/main/java/it/blackhat/symposium/actions/admin/SignoutAdmin.java
- src/main/java/it/blackhat/symposium/actions/guest/SigninAction.java
- src/main/java/it/blackhat/symposium/actions/stats/GenerateStatsAction.java
- src/main/java/it/blackhat/symposium/actions/stats/StatsActionFactory.java
- src/main/java/it/blackhat/symposium/actions/user/BanAction.java
- src/main/java/it/blackhat/symposium/controllers/StatsController.java
- src/main/webapp/WEB-INF/tags/questionOverview.tag
- src/main/webapp/adminSignup.jsp
- src/main/webapp/answerList.jsp
- src/main/webapp/questionList.jsp
- src/main/webapp/reportList.jsp
- src/main/webapp/userList.jsp
Add admin pages, StatsController, refactor some thing
> add admin pages, statscontroller, refactor things

- src/main/java/it/blackhat/symposium/actions/guest/SigninAction.java
- src/main/java/it/blackhat/symposium/actions/guest/SignupAction.java
> Signin & Signup Finally working

- src/main/java/it/blackhat/symposium/actions/question/AddFavouriteAction.java
- src/main/java/it/blackhat/symposium/actions/question/ShowQuestionAction.java
- src/main/java/it/blackhat/symposium/managers/QuestionManager.java
- src/main/java/it/blackhat/symposium/managers/QuestionModelManager.java
Adding some methods to QuestionManager and QuestionModelManager.
Adding AddFavouriteAction.
> AngeloPullRequest

- src/main/java/it/blackhat/symposium/actions/guest/GuestActionFactory.java
- src/main/java/it/blackhat/symposium/actions/question/SeachQuestionsBy.java
- src/main/webapp/WEB-INF/tags/questionResearch.tag
- src/main/webapp/searchResult.jsp
Added searchResult.jsp and questionResearch.tag
Modified SearchQuestionBy and GuestActionFactory
Added searchResult.jsp and questionResearch.tag
Added showQuestionAction case in GuestActionFactory
Modified SearchQuestionBy
> Front End SearchQuestion

- src/main/java/it/blackhat/symposium/actions/guest/SigninAction.java
- src/main/java/it/blackhat/symposium/actions/guest/SignupAction.java
- src/main/java/it/blackhat/symposium/actions/user/EditProfileAction.java
- src/main/java/it/blackhat/symposium/managers/UserModelManager.java
- src/main/java/it/blackhat/symposium/models/AnswerModel.java
- src/main/java/it/blackhat/symposium/models/QuestionModel.java
- src/main/java/it/blackhat/symposium/models/ReportModel.java
- src/main/java/it/blackhat/symposium/models/StatsModel.java
- src/main/java/it/blackhat/symposium/models/TagModel.java
- src/main/java/it/blackhat/symposium/models/UserModel.java
- src/main/webapp/editProfile.jsp
Edit Profile Fix.
Added method toString() for all models
> Fix Edit Profile & ToString() method

- src/main/java/it/blackhat/symposium/actions/guest/SigninAdminAction.java
- src/main/java/it/blackhat/symposium/managers/AdminModelManager.java
- src/main/java/it/blackhat/symposium/queries/AdminQuery.java
> Fix Admin Signup

- src/main/java/it/blackhat/symposium/actions/guest/SigninAction.java
- src/main/java/it/blackhat/symposium/actions/guest/SignupAction.java
- src/main/webapp/signIn.jsp
- src/main/webapp/signUp.jsp
I've added some error messages when an user tries to login with a non-existing password and when tries
to signUp with an email that is already in the database
Addedd error messages
> Added error messages

- src/main/java/it/blackhat/symposium/actions/question/InsertQuestionAction.java
- src/main/java/it/blackhat/symposium/actions/question/QuestionActionFactory.java
- src/main/java/it/blackhat/symposium/actions/tag/InsertTagAction.java
- src/main/java/it/blackhat/symposium/managers/TagManager.java
- src/main/webapp/assets/index.js
- src/main/webapp/newQuestion.jsp
Adding newQuestion.jsp, InsertTagAction and some methods in InsertQuestionAction,QuestionActionFactory,TagManager.
> Adding newQuestion.jsp, InsertTagAction and some methods in InsertQuestionAction,QuestionActionFactory,TagManager.

- src/main/java/it/blackhat/symposium/actions/tag/InsertTagAction.java
- src/main/java/it/blackhat/symposium/managers/AdminManager.java
- src/main/java/it/blackhat/symposium/managers/AdminModelManager.java
- src/main/java/it/blackhat/symposium/managers/AnswerManager.java
- src/main/java/it/blackhat/symposium/managers/AnswerModelManager.java
- src/main/java/it/blackhat/symposium/managers/QuestionManager.java
- src/main/java/it/blackhat/symposium/managers/QuestionModelManager.java
- src/main/java/it/blackhat/symposium/managers/ReportManager.java
- src/main/java/it/blackhat/symposium/managers/ReportModelManager.java
- src/main/java/it/blackhat/symposium/managers/TagManager.java
- src/main/java/it/blackhat/symposium/managers/TagModelManager.java
- src/main/java/it/blackhat/symposium/managers/UserManager.java
- src/main/java/it/blackhat/symposium/managers/UserModelManager.java
- src/main/java/it/blackhat/symposium/models/Report.java
- src/main/java/it/blackhat/symposium/models/ReportModel.java
- src/main/java/it/blackhat/symposium/queries/AdminQuery.java
- src/main/java/it/blackhat/symposium/queries/AnswerQuery.java
- src/main/java/it/blackhat/symposium/queries/QuestionQuery.java
- src/main/java/it/blackhat/symposium/queries/ReportQuery.java
- src/main/java/it/blackhat/symposium/queries/TagQuery.java
- src/main/java/it/blackhat/symposium/queries/UserQuery.java
fixed: queries, models, managers and modelmanagers
added: queries, models, managers and modelmanagers
> fixed and added queries,model,managers and modelManagers

- src/main/java/it/blackhat/symposium/actions/question/AddFavouriteAction.java
- src/main/java/it/blackhat/symposium/actions/question/QuestionActionFactory.java
- src/main/java/it/blackhat/symposium/managers/QuestionManager.java
- src/main/java/it/blackhat/symposium/managers/QuestionModelManager.java
- src/main/webapp/WEB-INF/tags/questionDetails.tag
- src/main/webapp/question.jsp
Modified QuestionModelManager, QuestionModel, question.jsp, questionDetals.tag, AddFavouriteAction, QuestionActionFactory
Added Case in QuestionActionFactory
Minor Fixes in AddFavourite, QuestionManager and QuestionModelManager
Added Form in question.jsp-questionDetails.tag
> Front End AddFavourite

- src/main/java/it/blackhat/symposium/actions/admin/AdminActionFactory.java
- src/main/java/it/blackhat/symposium/actions/admin/ShowUsersAction.java
- src/main/webapp/WEB-INF/tags/userOverview.tag
- src/main/webapp/partials/header.jsp
- src/main/webapp/userList.jsp
Added ShowUserList.action  + other minor things
Added ShowUserList.action
Added ShowUserList.jsp 
Modified AdminActionFactory.java
Modified the header
Modified userList.jsp
> ShowUserList.action

- src/main/java/it/blackhat/symposium/actions/question/InsertQuestionAction.java
- src/main/java/it/blackhat/symposium/managers/TagModelManager.java
- src/main/java/it/blackhat/symposium/queries/TagQuery.java
added Query: insertTag, fixed newQuestionAction.java
> added query, fixed new Question

- src/main/java/it/blackhat/symposium/actions/user/BanAction.java
- src/main/java/it/blackhat/symposium/actions/user/UserActionFactory.java
- src/main/webapp/WEB-INF/tags/userOverview.tag
- src/main/webapp/stats.jsp
- src/main/webapp/userList.jsp
> Ban Action stuff

- src/main/java/it/blackhat/symposium/actions/question/InsertQuestionAction.java
- src/main/java/it/blackhat/symposium/actions/question/QuestionActionFactory.java
- src/main/java/it/blackhat/symposium/actions/stats/UpdateStatsAction.java
- src/main/java/it/blackhat/symposium/actions/tag/InsertTagAction.java
- src/main/java/it/blackhat/symposium/helpers/TagExtractor.java
- src/main/java/it/blackhat/symposium/managers/AdminModelManager.java
- src/main/java/it/blackhat/symposium/managers/AnswerModelManager.java
- src/main/java/it/blackhat/symposium/managers/QuestionManager.java
- src/main/java/it/blackhat/symposium/managers/QuestionModelManager.java
- src/main/java/it/blackhat/symposium/managers/StatsManager.java
- src/main/java/it/blackhat/symposium/managers/StatsModelManager.java
- src/main/java/it/blackhat/symposium/models/StatsModel.java
- src/main/java/it/blackhat/symposium/queries/AdminQuery.java
- src/main/java/it/blackhat/symposium/queries/AnswerQuery.java
- src/main/java/it/blackhat/symposium/queries/QuestionQuery.java
- src/main/java/it/blackhat/symposium/queries/ReportQuery.java
- src/main/java/it/blackhat/symposium/queries/StatsQuery.java
- src/main/java/it/blackhat/symposium/queries/TagQuery.java
- src/main/java/it/blackhat/symposium/queries/UserQuery.java
Finished InsertQuestion, fixed BanQuery and fixed classes for the checkstyle
> finished InsertQuestion

- src/main/java/it/blackhat/symposium/actions/question/AddFavouriteAction.java
- src/main/java/it/blackhat/symposium/actions/question/InsertQuestionAction.java
- src/main/java/it/blackhat/symposium/actions/question/QuestionActionFactory.java
- src/main/java/it/blackhat/symposium/actions/question/ShowNewQuestionAction.java
- src/main/java/it/blackhat/symposium/actions/user/ShowEditProfileAction.java
- src/main/java/it/blackhat/symposium/actions/user/ShowProfileAction.java
- src/main/java/it/blackhat/symposium/actions/user/UserActionFactory.java
- src/main/webapp/WEB-INF/tags/layout.tag
- src/main/webapp/assets/index.css
- src/main/webapp/assets/index.js
- src/main/webapp/newQuestion.jsp
- src/main/webapp/partials/header.jsp
- src/main/webapp/profile.jsp
I fixed style of tags and some async loading. I have added some action and fix some header's link too
> fix style custom tags and edit showprofile

- src/main/webapp/WEB-INF/tags/layout.tag
- src/main/webapp/partials/header.jsp
> fix relative path issues

- src/main/java/it/blackhat/symposium/actions/answer/DeleteAnswerByQuestionAction.java
- src/main/java/it/blackhat/symposium/actions/question/DeleteQuestionAction.java
- src/main/java/it/blackhat/symposium/actions/question/QuestionActionFactory.java
- src/main/java/it/blackhat/symposium/managers/AnswerManager.java
- src/main/java/it/blackhat/symposium/managers/AnswerModelManager.java
- src/main/java/it/blackhat/symposium/queries/AnswerQuery.java
- src/main/java/it/blackhat/symposium/queries/QuestionQuery.java
- src/main/java/it/blackhat/symposium/queries/ReportQuery.java
- src/main/java/it/blackhat/symposium/queries/StatsQuery.java
- src/main/java/it/blackhat/symposium/queries/UserQuery.java
> finished DeleteQuestion

- src/main/java/it/blackhat/symposium/actions/question/QuestionActionFactory.java
- src/main/java/it/blackhat/symposium/actions/question/ShowFavoriteAction.java
- src/main/java/it/blackhat/symposium/managers/QuestionManager.java
- src/main/java/it/blackhat/symposium/managers/QuestionModelManager.java
- src/main/java/it/blackhat/symposium/queries/QuestionQuery.java
- src/main/webapp/WEB-INF/tags/questionDetails.tag
- src/main/webapp/favoriteQuestion.jsp
- src/main/webapp/partials/header.jsp
Added favoriteQuestion.jsp, ShowFavorite
Modified QuestionActionFactory, QuestionManager, header, questionDetails, questionQuer
> Added ShowFavorite

- src/main/java/it/blackhat/symposium/actions/guest/SignupAction.java
- src/main/webapp/adminSignIn.jsp
- src/main/webapp/signIn.jsp
- src/main/webapp/signUp.jsp
I've refactored signIn , signUp and adminSignIn.
Written the rewritten variable log name in SignupAction.java
Added the right regex and various fixes overall adminSignIn.jsp
fixed the regex in signIn.jsp and signUp.jsp
> Refactored signIn , signUp and adminSignIn

- src/main/java/it/blackhat/symposium/actions/guest/SignupAction.java
- src/main/java/it/blackhat/symposium/actions/question/DeleteQuestionAction.java
- src/main/java/it/blackhat/symposium/actions/stats/GenerateStatsAction.java
- src/main/java/it/blackhat/symposium/actions/stats/ShowStatsViewAction.java
- src/main/java/it/blackhat/symposium/actions/stats/StatsActionFactory.java
- src/main/java/it/blackhat/symposium/managers/StatsModelManager.java
- src/main/java/it/blackhat/symposium/managers/TagManager.java
- src/main/java/it/blackhat/symposium/managers/TagModelManager.java
- src/main/java/it/blackhat/symposium/managers/UserModelManager.java
- src/main/java/it/blackhat/symposium/models/User.java
- src/main/java/it/blackhat/symposium/models/UserModel.java
- src/main/java/it/blackhat/symposium/queries/TagQuery.java
- src/main/java/it/blackhat/symposium/queries/UserQuery.java
- src/main/webapp/WEB-INF/tags/stats.tag
- src/main/webapp/partials/header.jsp
- src/main/webapp/stats.jsp
Almost completed GenerateReport
> Almost completed GenerateReport

- src/main/java/it/blackhat/symposium/actions/stats/GenerateStatsAction.java
- src/main/java/it/blackhat/symposium/helpers/MapCompleteHandler.java
- src/main/java/it/blackhat/symposium/managers/QuestionModelManager.java
- src/main/java/it/blackhat/symposium/managers/TagManager.java
- src/main/java/it/blackhat/symposium/managers/TagModelManager.java
- src/main/java/it/blackhat/symposium/queries/QuestionQuery.java
- src/main/webapp/WEB-INF/tags/stats.tag
- src/main/webapp/index.jsp
- src/main/webapp/partials/header.jsp
- src/main/webapp/stats.jsp
fix header conflict and report
> fix header conflict and finish report

- src/main/java/it/blackhat/symposium/actions/guest/GuestActionFactory.java
- src/main/java/it/blackhat/symposium/actions/question/QuestionActionFactory.java
- src/main/java/it/blackhat/symposium/actions/question/SeachQuestionByAction.java
- src/main/webapp/partials/header.jsp
Modification to GuestActionFactory, QuestionActionFactory, header.jsp
> Fix To Search

- src/main/java/it/blackhat/symposium/actions/guest/GuestActionFactory.java
- src/main/java/it/blackhat/symposium/actions/question/ShowQuestionsAction.java
- src/main/java/it/blackhat/symposium/controllers/GuestController.java
- src/main/java/it/blackhat/symposium/controllers/QuestionController.java
- src/main/java/it/blackhat/symposium/controllers/UserController.java
- src/main/java/it/blackhat/symposium/helpers/QuestionTag.java
- src/main/java/it/blackhat/symposium/queries/QuestionQuery.java
- src/main/webapp/WEB-INF/tags/question.tag
- src/main/webapp/WEB-INF/web.xml
- src/main/webapp/index.jsp
Fix index page & questionController 
> Fix index page

- src/main/java/it/blackhat/symposium/actions/question/QuestionActionFactory.java
- src/main/java/it/blackhat/symposium/actions/question/ShowQuestionsAction.java
- src/main/java/it/blackhat/symposium/controllers/GuestController.java
- src/main/java/it/blackhat/symposium/controllers/QuestionController.java
- src/main/webapp/WEB-INF/web.xml
- src/main/webapp/allQuestions.jsp
- src/main/webapp/index.jsp
fix redirect and avoid null checking
> fix showallQuestions

- src/main/java/it/blackhat/symposium/actions/tag/ChangeTagAction.java
- src/main/java/it/blackhat/symposium/managers/TagManager.java
- src/main/java/it/blackhat/symposium/managers/TagModelManager.java
- src/main/java/it/blackhat/symposium/queries/TagQuery.java
- src/main/webapp/WEB-INF/tags/questionDetails.tag
- src/main/webapp/WEB-INF/tags/tagDetails.tag
Modified ChangeTagAction, TagManager, TagModelManager, questionDetails, tagDetails and TagQuery
> Fix to ChangeTag

- src/main/java/it/blackhat/symposium/actions/answer/InsertAnswerAction.java
- src/main/java/it/blackhat/symposium/actions/guest/SignupAction.java
- src/main/java/it/blackhat/symposium/actions/question/InsertQuestionAction.java
> Added BeanValidators

- src/main/webapp/adminSignIn.jsp
- src/main/webapp/allQuestions.jsp
- src/main/webapp/reportList.jsp
- src/main/webapp/userList.jsp
Improved visualitation in:
adminSignIn.jsp
allQuestions.jsp
reportList.jsp
userList.jsp
> Improved visualization

- src/main/webapp/adminSignIn.jsp
- src/main/webapp/newAnswer.jsp
adminSignIn.jsp newAnswer.jsp frontend fix
> adminSignIn.jsp newAnswer.jsp frontend fix

- src/main/java/it/blackhat/symposium/actions/answer/AnswerActionFactory.java
- src/main/java/it/blackhat/symposium/actions/answer/InsertAnswerAction.java
- src/main/java/it/blackhat/symposium/actions/answer/ShowAnswerPage.java
- src/main/webapp/WEB-INF/tags/questionDetails.tag
- src/main/webapp/newAnswer.jsp
> add show newanswer

- src/main/java/it/blackhat/symposium/actions/answer/InsertAnswerAction.java
- src/main/webapp/newAnswer.jsp
Fix Validation in Inser Answer
- [ x] Bug fix (non-breaking change which fixes an issue)
> Fix Answer Validation

- src/main/java/it/blackhat/symposium/actions/question/QuestionActionFactory.java
- src/main/java/it/blackhat/symposium/actions/question/ShowMyQuestion.java
- src/main/java/it/blackhat/symposium/managers/QuestionManager.java
- src/main/java/it/blackhat/symposium/managers/QuestionModelManager.java
- src/main/java/it/blackhat/symposium/queries/QuestionQuery.java
- src/main/webapp/partials/header.jsp
Completed ShowMyQuestion (in 20 minutes)
> ShowMyQuestion completata

- src/main/webapp/WEB-INF/tags/report.tag
Fix Show Report for admin
- [x ] Bug fix (non-breaking change which fixes an issue)
> Fix show Report for admin

- src/main/webapp/WEB-INF/tags/answer.tag
- src/main/webapp/WEB-INF/tags/questionDetails.tag
> refactor questionview

- src/main/java/it/blackhat/symposium/actions/user/EditProfileAction.java
- src/main/webapp/editProfile.jsp
- src/main/webapp/profile.jsp
> Fixed editprofile

- src/main/java/it/blackhat/symposium/models/StatsModel.java
- src/test/java/it/blackhat/symposium/unit/StatsActionFactoryTest.java
- src/test/java/it/blackhat/symposium/unit/StatsModelManagerTest.java
- src/test/java/it/blackhat/symposium/unit/StatsModelTest.java
Please include a summary of the change and which issue is fixed. Please also include relevant 
motivation and context. List any dependencies that are required for this change.
> Added the tests for StatsActionFactory, StatsModelManager and StatsModel

- src/main/java/it/blackhat/symposium/models/StatsModel.java
- src/test/java/it/blackhat/symposium/unit/AdminActionFactoryTest.java
- src/test/java/it/blackhat/symposium/unit/AdminModelManagerConstractorTest.java
- src/test/java/it/blackhat/symposium/unit/AdminModelManagerTest.java
- src/test/java/it/blackhat/symposium/unit/AdminModelTest.java
- src/test/java/it/blackhat/symposium/unit/StatsActionFactoryTest.java
- src/test/java/it/blackhat/symposium/unit/StatsModelManagerTest.java
- src/test/java/it/blackhat/symposium/unit/StatsModelTest.java
AdminActionFactoryTest, AdminModelTest and AdminModelManagerTest
> Complete admin Test

- src/test/java/it/blackhat/symposium/unit/StatsModelTest.java
- src/test/java/it/blackhat/symposium/unit/UnitTestSuite.java
- src/test/java/it/blackhat/symposium/unit/UserActionFactoryTest.java
- src/test/java/it/blackhat/symposium/unit/UserModelManagerTest.java
- src/test/java/it/blackhat/symposium/unit/UserModelTest.java
Added UserModelTest
Added UserModelMangerTest
Added UserActionFactory
> Added TestUser

- pom.xml
- src/main/java/it/blackhat/symposium/managers/ConnectionManager.java
- src/test/java/it/blackhat/symposium/unit/BeanValidatorTest.java
- src/test/java/it/blackhat/symposium/unit/QuestionActionFactoryTest.java
- src/test/java/it/blackhat/symposium/unit/QuestionModelManagerTest.java
- src/test/java/it/blackhat/symposium/unit/QuestionModelTest.java
- src/test/java/it/blackhat/symposium/unit/UnitTestSuite.java
Created all question's related tests and prototype of beanvalidator test
> Created Question related tests and BeanValidator test prototype

- src/test/java/it/blackhat/symposium/integration/IntegrationTestSuite.java
- src/test/resources/dump.sql
add a dump db for integration testing
> add dump db

- pom.xml
- src/main/webapp/signIn.jsp
- src/test/java/it/blackhat/symposium/system/SystemTestSuite.java
Added Configuration for System Test & Example
> Example System Test

- src/test/java/it/blackhat/symposium/integration/AdminManagerTest.java
> AdminModelTest

- src/test/java/it/blackhat/symposium/system/TestUserLogin.java
> Example System 

- src/main/java/it/blackhat/symposium/managers/StatsModelManager.java
- src/test/java/it/blackhat/symposium/integration/AdminManagerTest.java
- src/test/java/it/blackhat/symposium/integration/IntegrationTestSuite.java
- src/test/java/it/blackhat/symposium/integration/StatsModelManagerDBTest.java
- src/test/resources/dump.sql
There are problem with testUpdateStatsTag maybe due to the sql dump or the query
> Intergration Test done 

- src/test/java/it/blackhat/symposium/unit/QuestionTagTest.java
> QuestionTagTest

- src/main/java/it/blackhat/symposium/actions/question/AddFavouriteAction.java
- src/main/java/it/blackhat/symposium/actions/question/QuestionActionFactory.java
- src/main/java/it/blackhat/symposium/actions/question/SeachQuestionByAction.java
- src/main/java/it/blackhat/symposium/managers/QuestionManager.java
- src/main/java/it/blackhat/symposium/managers/QuestionModelManager.java
- src/main/java/it/blackhat/symposium/models/QuestionModel.java
- src/main/java/it/blackhat/symposium/queries/QuestionQuery.java
- src/main/webapp/partials/header.jsp
- src/main/webapp/signUp.jsp
- src/test/java/it/blackhat/symposium/system/TestUserLogin.java
> Fixxed Search

- src/main/java/it/blackhat/symposium/controllers/DispatcherController.java
- src/main/webapp/newQuestion.jsp
- src/test/java/it/blackhat/symposium/integration/AnswerModelManagerTest.java
> fix character encoding

- src/main/java/it/blackhat/symposium/actions/stats/GenerateStatsAction.java
- src/main/java/it/blackhat/symposium/managers/TagModelManager.java
- src/main/webapp/partials/header.jsp
- src/main/webapp/profile.jsp
> Fixed sorting

- src/main/java/it/blackhat/symposium/actions/question/AddFavouriteAction.java
- src/main/java/it/blackhat/symposium/actions/tag/RetrieveQuestionTagsAction.java
- src/main/java/it/blackhat/symposium/actions/tag/TagActionFactory.java
- src/main/java/it/blackhat/symposium/actions/user/DeleteAccountAction.java
- src/main/java/it/blackhat/symposium/actions/user/UserActionFactory.java
- src/main/webapp/WEB-INF/tags/questionDetails.tag
- src/main/webapp/WEB-INF/tags/tagDetails.tag
- src/main/webapp/editTag.jsp
- src/main/webapp/partials/header.jsp
- src/main/webapp/profile.jsp
> merge delete account and chage tag from Gozzetto

- src/main/java/it/blackhat/symposium/actions/answer/ChooseBestAnswerAction.java
- src/main/webapp/WEB-INF/tags/answer.tag
- src/main/webapp/WEB-INF/tags/questionDetails.tag
Final commit by @didacusAbella. Fixbest answer @2Deimos 
> add best answer

- src/main/java/it/blackhat/symposium/actions/question/AddFavouriteAction.java
- src/main/java/it/blackhat/symposium/actions/question/SeachQuestionByAction.java
- src/main/java/it/blackhat/symposium/actions/stats/GenerateStatsAction.java
- src/main/java/it/blackhat/symposium/managers/QuestionManager.java
- src/main/java/it/blackhat/symposium/managers/QuestionModelManager.java
- src/main/java/it/blackhat/symposium/models/QuestionModel.java
- src/main/java/it/blackhat/symposium/queries/QuestionQuery.java
- src/main/webapp/WEB-INF/tags/questionOverview.tag
- src/main/webapp/editProfile.jsp
- src/main/webapp/newAnswer.jsp
- src/test/java/it/blackhat/symposium/system/SystemTestSuite.java
- src/test/java/it/blackhat/symposium/system/TestDeleteQuestionUser.java
- src/test/java/it/blackhat/symposium/system/TestNewAnswer.java
>  Added System test for newAnswer,some checkStyle Fixes and test for DeleteQuestionUser

- src/test/java/it/blackhat/symposium/integration/TagManagerTest.java
Fixed retrieveQuestionTagsTest assert.
> Fixed retrieveQuestionTagsTest assert.

- pom.xml
- src/main/java/it/blackhat/symposium/actions/user/EditProfileAction.java
- src/main/java/it/blackhat/symposium/models/UserModel.java
- src/main/webapp/editProfile.jsp
- src/test/java/it/blackhat/symposium/InizializerForSystemTesting.java
- src/test/java/it/blackhat/symposium/system/SystemTestSuite.java
- src/test/java/it/blackhat/symposium/system/TestUserEditProfile.java
- src/test/java/it/blackhat/symposium/system/TestUserSignUp.java
> Added EditProfileTest and Fixed EditProfile

- src/main/java/it/blackhat/symposium/managers/ReportModelManager.java
- src/main/java/it/blackhat/symposium/queries/ReportQuery.java
- src/test/java/it/blackhat/symposium/integration/ReportManagerTest.java
- src/test/java/it/blackhat/symposium/unit/ReportActionFactoryTest.java
- src/test/java/it/blackhat/symposium/unit/ReportModelManagerTest.java
- src/test/java/it/blackhat/symposium/unit/ReportModelTest.java
add unit and integration test for report. Fixed report manager insert
> Ad report test finally

- src/main/java/it/blackhat/symposium/actions/tag/ChangeTagAction.java
- src/main/webapp/WEB-INF/tags/tagDetails.tag
fix edit tag to accept multiple tag editing
> fix edit tag

- src/main/java/it/blackhat/symposium/actions/tag/ChangeTagAction.java
- src/main/webapp/WEB-INF/tags/answer.tag
- src/main/webapp/WEB-INF/tags/tagDetails.tag
- src/main/webapp/editTag.jsp
- src/test/java/it/blackhat/symposium/system/TestAdminBanUser.java
- src/test/java/it/blackhat/symposium/system/TestAdminChangeTag.java
- src/test/java/it/blackhat/symposium/system/TestAdminLogOut.java
- src/test/java/it/blackhat/symposium/system/TestAdminLogin.java
- src/test/java/it/blackhat/symposium/system/TestDeleteQuestionUser.java
- src/test/java/it/blackhat/symposium/system/TestNewAnswer.java
- src/test/java/it/blackhat/symposium/system/TestUserBestAnswer.java
- src/test/java/it/blackhat/symposium/system/TestUserDeleteAccount.java
- src/test/java/it/blackhat/symposium/system/TestUserDeleteQuestion.java
- src/test/java/it/blackhat/symposium/system/TestUserEditProfile.java
- src/test/java/it/blackhat/symposium/system/TestUserFavouriteQuestion.java
- src/test/java/it/blackhat/symposium/system/TestUserLogOut.java
- src/test/java/it/blackhat/symposium/system/TestUserLogin.java
- src/test/java/it/blackhat/symposium/system/TestUserNewQuestion.java
- src/test/java/it/blackhat/symposium/system/TestUserSearchByName.java
- src/test/java/it/blackhat/symposium/system/TestUserSearchByTag.java
- src/test/java/it/blackhat/symposium/system/TestUserSignUp.java
> System tests

- src/main/webapp/partials/header.jsp
- src/test/java/it/blackhat/symposium/system/SystemTestCase.java
- src/test/java/it/blackhat/symposium/system/TestShowReports.java
> adding testshowreports

- src/main/java/it/blackhat/symposium/actions/report/ReportQuestionAction.java
- src/main/java/it/blackhat/symposium/controllers/ReportController.java
- src/main/webapp/WEB-INF/tags/questionDetails.tag
- src/main/webapp/insertReport.jsp
> add report feature
